config/routes.rb
Rakerunner::Application.routes.draw do
  root :to => 'overview#index'

  resources :command_parameters

  resources :rake_files

  resources :rake_tasks

  resources :permissions

  resources :users

  resources :run_history

  match 'run/:rake_file/:task' => 'rake_files#run'

  match 'overview' => 'overview#index'

  match 'twilio' => 'twilio#index'

  match 'login' => 'users#login'
  
  match 'logout' => 'users#logout'

  match 'run_history/:id/output' => 'run_history#output'

  match 'run_history/:id/tail/:line' => 'run_history#tail_output'

end

app/models/rake_file.rb
class RakeFile < ActiveRecord::Base
  attr_accessible :active, :file_name, :path
  has_one :user 
  has_many :rake_task

end

app/controllers/rake_files_controller.rb
class RakeFilesController < ApplicationController
  # GET /rake_files
  # GET /rake_files.json
  def index
    @rake_files = RakeFile.where(:active=>true);

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rake_files }
    end
  end

  def run  
    task = RakeTask.joins(:rake_file).where(:task=>params["task"], :rake_files=>{:file_name=>params[:rake_file]}).first
    @run_history = task.delay_run 
    

    respond_to do |format|
      format.html
      format.json {render json: @run_history.output} 
    end
  end

  # GET /rake_files/1
  # GET /rake_files/1.json
  def show
    @rake_file = RakeFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rake_file }
    end
  end

  # GET /rake_files/new
  # GET /rake_files/new.json
  def new
    @rake_file = RakeFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rake_file }
    end
  end

  # GET /rake_files/1/edit
  def edit
    @rake_file = RakeFile.find(params[:id])
  end

  # POST /rake_files
  # POST /rake_files.json
  def create
    uploadFile = params[:rake_file][:file]
    fileName = uploadFile.original_filename.chomp(".rake")
    newFilePath = Rails.root.join('private', 'rake_files', "#{fileName}.rake")
    uploadFile = uploadFile.read
    taskNamesFound = Array.new
    #if File.exsits? newFilePath 
    #  fileName += Time.now.delete(' ')
    #end

    File.open(newFilePath, 'w') do |file|
      uploadFile.each_line do |line|
        line.scan(/^task ["'](.+)["']/) { |taskName| taskNamesFound.push taskName.first }
        file.puts line
      end
    end
    puts "number of task names:#{taskNamesFound.size}"

    @rake_file = RakeFile.new(:path=> newFilePath.to_s, :file_name => fileName,  :active=>true)

    respond_to do |format|
      if @rake_file.save
        taskNamesFound.each do |taskName|
          puts "adding taskName: #{taskName}"
          @rake_file.rake_task.create(:task => taskName, :active=>true)
        end
        format.html { redirect_to @rake_file, notice: 'Rake file was successfully created.' }
        format.json { render json: @rake_file, status: :created, location: @rake_file }
      else
        format.html { render action: "new" }
        format.json { render json: @rake_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rake_files/1
  # PUT /rake_files/1.json
  def update
    @rake_file = RakeFile.find(params[:id])

    respond_to do |format|
      if @rake_file.update_attributes(params[:rake_file])
        format.html { redirect_to @rake_file, notice: 'Rake file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rake_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rake_files/1
  # DELETE /rake_files/1.json
  def destroy
    @rake_file = RakeFile.find(params[:id])
    @rake_file.destroy

    respond_to do |format|
      format.html { redirect_to rake_files_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rake_files_helper.rb
module RakeFilesHelper
end

app/views/rake_files/_form.html.erb
<%= form_for(@rake_file) do |f| %>
  <% if @rake_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rake_file.errors.count, "error") %> prohibited this rake_file from being saved:</h2>

      <ul>
      <% @rake_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="upload">

    <%= f.label :file %><br />
    <%= f.file_field :file%><br />
    
  </div> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rake_files/edit.html.erb
<h1>Editing rake_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @rake_file %> |
<%= link_to 'Back', rake_files_path %>

app/views/rake_files/index.html.erb
<div class="row">
<h1>Rake Files Uploaded</h1>
  <div class="span6">
    <table class="table table-striped">
      <tr>
        <th>Filename</th>
      </tr>

    <% @rake_files.each do |rake_file| %>
      <tr>
        <td><%= rake_file.file_name %></td>
      </tr>
    <% end %>
    </table>
  <div>
</div>
<br />

<%= link_to 'New Rake file', new_rake_file_path %>

app/views/rake_files/new.html.erb
<h1>New rake_file</h1>

<%= render 'form' %>

<%= link_to 'Back', rake_files_path %>

app/views/rake_files/run.html.erb
<h1>You just ran a rake file </h1>
<p> It's output can be found in run history id <%= @run_history.id%> </p>
<p> <%= link_to "output", "/run_history/#{@run_history.id}/output.json" %> </p>
<p> <%= link_to "after line 2", "/run_history/#{@run_history.id}/tail/2.json" %> </p>

app/views/rake_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Active:</b>
  <%= @rake_file.active %>
</p>

<p>
  <b>Path:</b>
  <%= @rake_file.path %>
</p>

<p>
  <b>Filename:</b>
  <%= @rake_file.file_name %>
</p>


<%= link_to 'Edit', edit_rake_file_path(@rake_file) %> |
<%= link_to 'Back', rake_files_path %>