config/routes.rb
Rakerunner::Application.routes.draw do
  root :to => 'overview#index'

  resources :command_parameters

  resources :rake_files

  resources :rake_tasks

  resources :permissions

  resources :users

  resources :run_history

  match 'run/:rake_file/:task' => 'rake_files#run'

  match 'overview' => 'overview#index'

  match 'twilio' => 'twilio#index'

  match 'login' => 'users#login'
  
  match 'logout' => 'users#logout'

  match 'run_history/:id/output' => 'run_history#output'

  match 'run_history/:id/tail/:line' => 'run_history#tail_output'

end

app/models/command_parameter.rb
class CommandParameter < ActiveRecord::Base
  attr_accessible :name, :type
  belongs_to :rake_task
end

app/controllers/command_parameters_controller.rb
class CommandParametersController < ApplicationController
  # GET /command_parameters
  # GET /command_parameters.json
  def index
    @command_parameters = CommandParameter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @command_parameters }
    end
  end

  # GET /command_parameters/1
  # GET /command_parameters/1.json
  def show
    @command_parameter = CommandParameter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @command_parameter }
    end
  end

  # GET /command_parameters/new
  # GET /command_parameters/new.json
  def new
    @command_parameter = CommandParameter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @command_parameter }
    end
  end

  # GET /command_parameters/1/edit
  def edit
    @command_parameter = CommandParameter.find(params[:id])
  end

  # POST /command_parameters
  # POST /command_parameters.json
  def create
    @command_parameter = CommandParameter.new(params[:command_parameter])

    respond_to do |format|
      if @command_parameter.save
        format.html { redirect_to @command_parameter, notice: 'Command parameter was successfully created.' }
        format.json { render json: @command_parameter, status: :created, location: @command_parameter }
      else
        format.html { render action: "new" }
        format.json { render json: @command_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /command_parameters/1
  # PUT /command_parameters/1.json
  def update
    @command_parameter = CommandParameter.find(params[:id])

    respond_to do |format|
      if @command_parameter.update_attributes(params[:command_parameter])
        format.html { redirect_to @command_parameter, notice: 'Command parameter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @command_parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /command_parameters/1
  # DELETE /command_parameters/1.json
  def destroy
    @command_parameter = CommandParameter.find(params[:id])
    @command_parameter.destroy

    respond_to do |format|
      format.html { redirect_to command_parameters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/command_parameters_helper.rb
module CommandParametersHelper
end

app/views/command_parameters/_form.html.erb
<%= form_for(@command_parameter) do |f| %>
  <% if @command_parameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command_parameter.errors.count, "error") %> prohibited this command_parameter from being saved:</h2>

      <ul>
      <% @command_parameter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/command_parameters/edit.html.erb
<h1>Editing command_parameter</h1>

<%= render 'form' %>

<%= link_to 'Show', @command_parameter %> |
<%= link_to 'Back', command_parameters_path %>

app/views/command_parameters/index.html.erb
<h1>Listing command_parameters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @command_parameters.each do |command_parameter| %>
  <tr>
    <td><%= command_parameter.name %></td>
    <td><%= command_parameter.type %></td>
    <td><%= link_to 'Show', command_parameter %></td>
    <td><%= link_to 'Edit', edit_command_parameter_path(command_parameter) %></td>
    <td><%= link_to 'Destroy', command_parameter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Command parameter', new_command_parameter_path %>

app/views/command_parameters/new.html.erb
<h1>New command_parameter</h1>

<%= render 'form' %>

<%= link_to 'Back', command_parameters_path %>

app/views/command_parameters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @command_parameter.name %>
</p>

<p>
  <b>Type:</b>
  <%= @command_parameter.type %>
</p>


<%= link_to 'Edit', edit_command_parameter_path(@command_parameter) %> |
<%= link_to 'Back', command_parameters_path %>